apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-app
  namespace: argocd
spec:
  project: default   # keep default for now

  source:
    repoURL: https://github.com/aravindroy1/Fitness_Tracker.git
    targetRevision: HEAD
    path: K8s

  destination:
    server: https://kubernetes.default.svc
    namespace: fitness-ns   # your namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true