apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7-jammy

          # 🔥 OOM trigger
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Triggering OOM...";
              data="";
              while true; do
                head -c 50M </dev/zero > /dev/null
              done

          ports:
            - containerPort: 27017

          resources:
            limits:
              memory: "56Mi"   # reduced for faster OOM
              cpu: "200m"
            requests:
              memory: "28Mi"
              cpu: "100m"

          volumeMounts:
            - name: akash-data
              mountPath: /data/db

      volumes:
        - name: akash-data
          emptyDir:
            sizeLimit: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
