apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fitness-tracker-app
  namespace: fitness-ns
spec:
  replicas: 2

  strategy:
    blueGreen:
      activeService: fitness-active-svc
      previewService: fitness-preview-svc
      autoPromotionEnabled: false

  selector:
    matchLabels:
      app: fitness-tracker-app

  template:
    metadata:
      labels:
        app: fitness-tracker-app
    spec:
      containers:
      - name: fitness-tracker-app
        image: pulkit197/fitness_tracker-master-copy3-fitness-app:v1.1.1
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: fitness-configmap
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "fitness-tracker-app"
        - name: DD_VERSION
          value: "1.0.0"